snakefile: workflow/Snakefile
use-conda: True
conda-frontend: mamba
rerun-incomplete: True
jobs: 5  # number of jobs (samples) to process at once 
latency-wait: 120
keep-going: True
configfile: inputs/config.yaml
keep-incomplete: False
# unlock: True

cluster: 
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --ntasks={resources.tasks}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.time}
    --job-name={rule}-%j
    --output="logs/{rule}/{wildcards}.out"
    --error="logs/{rule}/{wildcards}.err"

# adjust as needed (increase cpus_per_task and mem if files are larger)
default-resources: 
  - time="5-0"  # default time 
  - partition="sched_mit_chisholm"
  - mem=60000  # default memory 
  - cpus_per_task=5  # default threads/CPU/cores
  - tasks=1
